version: "3.8"

services:
  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATABASE=Shop
    volumes:
      - ./MongoDb/database-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped